### ISSUE TITLE
IG is preseent in fsh-finder but doesn't update

### ISSUE THREAD

**Issue by dhes** [FSHSchool/fsh-finder#11]
Hi! Thanks for provideing fsh-finder. 

I'm on the list now as Colonoscopy Polyp at https://github.com/dhes/ColonoscopyPolyp. Thanks for that. 

The problem is I update daily but the fsh-finder site shows my last update as 10 days ago. 

Thanks again!

DH

**Comment by dhes** [comment]
Figured out. Thank you. DH

**Comment by cmoesel** [comment]
Great! And sorry! We somehow missed this issue the first time around.  I'm glad you figured it out!
