### ISSUE TITLE
FSH Finder should show stats for default branch

### ISSUE THREAD

**Issue by cmoesel** [FSHSchool/fsh-finder#6]
FSH Finder appears to show stats for the most recent (?) branch rather than the default branch (e.g., `master` or `main`).  For example, this is the entry for davinci-pdex-formulary:
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/2278253/108279743-1395c380-714b-11eb-9f0f-d0c4894cda15.png">
It indicates that the project is in SUSHI 1.0 format.  But if you click the link to go to its repo on GitHub, you end up at the master branch, which is _not_ SUSHI 1.0 format:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/2278253/108279818-36c07300-714b-11eb-9ada-78911b0f1b2c.png">

There is a branch in that project that is SUSHI 1.0 format [v1.0.2a](https://github.com/HL7/davinci-pdex-formulary/tree/v1.0.2a), but I expected the stats to be based on the default branch -- so it seemed like a mistake at first.

I'd suggest that either FSH Finder show only stats for the default branch or that if it shows stats for a non-default branch, it makes it clear in the UI and the link to GitHub goes to that branch.

If you always show the default branch, I guess you will need to decide what to do for projects on which the default branch is not a SUSHI project at all, but there is a non-default branch which is.

**Comment by cmoesel** [comment]
OK, so I noticed this over the weekend:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/2278253/108736067-3f27fd80-74ff-11eb-8995-fa39ed5bef7d.png">

Was this always there?  I don't see any recent commits, so I'm assuming I just didn't notice this before.  This definitely helps and makes my request above less important.

**Comment by masnick** [comment]
@cmoesel --
> OK, so I noticed this over the weekend:
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/2278253/108736067-3f27fd80-74ff-11eb-8995-fa39ed5bef7d.png">
> 
> Was this always there? I don't see any recent commits, so I'm assuming I just didn't notice this before. This definitely helps and makes my request above less important.

This was always there 😄 

But I agree this behavior may be confusing. I've added a visual indicator when `fsh` isn't present on `main` or `master`:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/110426/116076323-15579800-a662-11eb-8f60-3fd47dee056f.png">

This will be deployed within the next few hours.
